version: '3'
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d

  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "registration_topic:1:1"
    depends_on:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"

  auth_service:
    build: ./auth_service
    ports:
      - "8000:8000"
    command: ["./wait-for-it.sh", "kafka:9092", "--", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - db
      - kafka
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - YANDEX_CLIENT_ID=${YANDEX_CLIENT_ID}
      - YANDEX_CLIENT_SECRET=${YANDEX_CLIENT_SECRET}

  telegram_worker:
    build: ./telegram_worker
    command: ["./wait-for-it.sh", "kafka:9092", "--", "python", "worker.py"]
    depends_on:
      - kafka
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHANNEL_CHAT_ID=${TELEGRAM_CHANNEL_CHAT_ID}